
DROP TABLE lists CASCADE;

DROP TABLE snippets CASCADE;

DROP TABLE favourite_snippets CASCADE;

DROP TABLE tags CASCADE;

DROP TABLE languages CASCADE;

DROP TABLE snippets_tags CASCADE;

DROP TABLE users CASCADE;
